# Butterfly 4.12.0 Config Override
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  关于: /about/ || fas fa-heart

avatar:
  img: /img/avatar.jpg
  effect: true

cover:
  index_enable: true
  aside_enable: false
  archives_enable: false
  position: both

index_img: /img/cover.jpg

social:
  fab fa-github: https://github.com/GeekQin || Github || '#24292e'
  fab fa-twitter: https://twitter.com/geekqin || Twitter || '#1DA1F2'
  fab fa-weixin: javascript:void(0) || 微信 || '#07C160'
  fas fa-envelope: mailto:geekqin@email.com || Email || '#4a7dbe'
  fab fa-bitcoin: https://partner.hdmune.cn/bg/XJWMF6 || 合约交易 || '#F7931A' 

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: false

fancybox: true

footer:
  owner:
    enable: true
    since: 2026
  copyright: true
  framework:
    enable: true
    text: Hexo
  theme:
    enable: true
    text: Butterfly

card_announcement:
  enable: true
  content: This is my Blog

card_recent_post:
  enable: true

post_meta:
  date_format: relative
  updated:
    enable: true
    date_format: relative
    relative: true

auto_excerpt:
  enable: false

darkmode:
  enable: true
  button: true
  autoDarkmode: false
