# Hexo Configuration
title: 币圈老秦's Blog
subtitle: ''
description: 币圈老秦的个人博客，分享Web3见解与交易心得，个人公众号：币圈老秦，欢迎骚扰！
author: 币圈老秦
language: zh-CN
timezone: Asia/Shanghai
url: https://geekqin.github.io
root: /
permalink: :year/:month/:day/:title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories

# Writing
new_post_name: :title.md
default_layout: post
auto_spacing: true

# Pagination
per_page: 10
pagination_dir: page

# Theme
theme: butterfly

# Deployment
deploy:
  type: git
  repo: https://github.com/GeekQin/GeekQin.github.io.git
  branch: gh-pages

# Extensions
plugins:
  - hexo-generator-feed
  - hexo-generator-sitemap
  - hexo-generator-search

feed:
  type: atom
  path: atom.xml
  limit: 20

sitemap:
  path: sitemap.xml

search:
  path: search.xml
  field: post
  content: true
